name: Flows ➡️

on:
  #push:
  #  branches:
  #    - master
  workflow_dispatch:

jobs:
  Paso1:
    runs-on: ubuntu-latest

    steps:
      - name: Paso 1
        run: echo 'Paso 1'

  Paso2-1:
    runs-on: ubuntu-latest
    needs: Paso1
    
    steps:
      - name: Paso 2-1
        run: echo 'Paso 2-1'

  Paso2-2:
    runs-on: ubuntu-latest
    needs: Paso1
    
    steps:
      - name: Paso 2-2
        run: echo 'Paso 2-2'

  Paso2-3:
    runs-on: ubuntu-latest
    needs: Paso1
    
    steps:
      - name: Paso 2-3
        run: echo 'Paso 2-3'

  Paso3:
    runs-on: ubuntu-latest
    needs: [Paso2-1, Paso2-2, Paso2-3]
    
    steps:
      - name: Paso 3-1
        run: echo 'Paso 3-1'

  Paso4:
    runs-on: ubuntu-latest
    needs: Paso3
    
    steps:
      - name: Paso 4
        run: echo 'Paso 4'        
        
